[2024-11-20T00:26:58.829+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-20T00:26:58.837+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data scheduled__2024-11-19T00:00:00+00:00 [queued]>
[2024-11-20T00:26:58.842+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data scheduled__2024-11-19T00:00:00+00:00 [queued]>
[2024-11-20T00:26:58.842+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2024-11-20T00:26:58.860+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2024-11-19 00:00:00+00:00
[2024-11-20T00:26:58.863+0000] {standard_task_runner.py:72} INFO - Started process 2724 to run task
[2024-11-20T00:26:58.869+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'transform_load_weather_data', 'scheduled__2024-11-19T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpk_7t0_dp']
[2024-11-20T00:26:58.872+0000] {standard_task_runner.py:105} INFO - Job 24: Subtask transform_load_weather_data
[2024-11-20T00:26:58.908+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_dag.transform_load_weather_data scheduled__2024-11-19T00:00:00+00:00 [running]> on host ip-172-31-82-42.ec2.internal
[2024-11-20T00:26:58.976+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-19T00:00:00+00:00'
[2024-11-20T00:26:58.977+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-20T00:26:58.977+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-20T00:26:58.978+0000] {logging_mixin.py:190} INFO - Current task name:transform_load_weather_data state:running start_date:2024-11-20 00:26:58.838334+00:00
[2024-11-20T00:26:58.978+0000] {logging_mixin.py:190} INFO - Dag name:weather_dag and current dag run status:running
[2024-11-20T00:26:58.979+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-20T00:26:58.983+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow/dags/weather_dag.py", line 43, in transform_load_data
    df_data = pd.DataFrame(transformed_data_list)
              ^^
NameError: name 'pd' is not defined
[2024-11-20T00:26:58.995+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-20T00:26:58.995+0000] {logging_mixin.py:190} INFO - Task start:2024-11-20 00:26:58.838334+00:00 end:2024-11-20 00:26:58.995065+00:00 duration:0.156731
[2024-11-20T00:26:58.996+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform_load_weather_data> dag:<DAG: weather_dag> dagrun:<DagRun weather_dag @ 2024-11-19 00:00:00+00:00: scheduled__2024-11-19T00:00:00+00:00, state:running, queued_at: 2024-11-20 00:26:42.373176+00:00. externally triggered: False>
[2024-11-20T00:26:58.996+0000] {logging_mixin.py:190} INFO - Failure caused by name 'pd' is not defined
[2024-11-20T00:26:58.996+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=transform_load_weather_data, run_id=scheduled__2024-11-19T00:00:00+00:00, execution_date=20241119T000000, start_date=20241120T002658, end_date=20241120T002658
[2024-11-20T00:26:59.013+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-20T00:26:59.013+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 24 for task transform_load_weather_data (name 'pd' is not defined; 2724)
Traceback (most recent call last):
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow/dags/weather_dag.py", line 43, in transform_load_data
    df_data = pd.DataFrame(transformed_data_list)
              ^^
NameError: name 'pd' is not defined
[2024-11-20T00:26:59.046+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-20T00:26:59.060+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-20T00:26:59.061+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
